### PR TITLE
Add Ruby 3.2 to CI.  Quote 3.0 so it isn't truncated.

### PR DESCRIPTION
**Pull request by petergoldstein**

### CODE REVIEW

**Comment by plentz** [comment]
The build is failing with a weird message, we need to investigate the cause

**Comment by plentz** [comment]
@petergoldstein [I've update codeclimate's plugin version](https://github.com/plentz/lol_dba/pull/144), I think that was the problem. Can you try updating your branch with code from `master`?

**Comment by petergoldstein** [comment]
@plentz I just rebased.

**Comment by plentz** [comment]
I've yolo-merged it to `master` and it worked https://github.com/plentz/lol_dba/actions/runs/4254909459. Probably something related with running `codeclimate` in other repos (your clone for example)

**Pull request merged**
