### PR TITLE
Has many through polymorphic

### PR DESCRIPTION
**Pull request by amnesia7**
For https://github.com/plentz/lol_dba/issues/25

### CODE REVIEW

**Comment by plentz** [comment]
@amnesia7 looks like this doesn't break the build. Are you sure that this is right? (sorry for taking so long to reply)

**Comment by amnesia7** [comment]
@plentz yes, that should give you a suitable setup to have a look into the polymorphic has many through issue. It is based on the model setup that I currently have.

**Comment by plentz** [comment]
@amnesia7 I'm testing this right now and looks like you forgot the Favourable class

**Comment by plentz** [comment]
thanks @amnesia7. this made me able to fix the thing :)

**Pull request merged**
